export type { ProjectSummary } from "@/features/workspace/workspace-types";
import type { ProjectSummary } from "@/features/workspace/workspace-types";

/** Test fixtures only — never used as live app defaults. */
export const demoProjects: ProjectSummary[] = [
  {
    id: "falcon-store",
    name: "تجارة الصقور",
    description: "بيع وشراء مستلزمات الصقور",
    status: "active",
    projectType: "birds",
    modules: {
      transactions: true,
      goal: false,
      workers: true,
      capital: true,
      inventory: true,
    livestock: false,
    },
    incomeMinor: 8_750_000n,
    expenseMinor: 4_470_000n,
    profitMinor: 4_280_000n,
    progress: 72,
    mark: "ص",
    tone: "bg-warning-soft text-warning",
    colorToken: "warning",
    outstandingLaborMinor: 0n,
    activeWorkers: 0,
    capitalMinor: 3_000_000n,
    capitalRecoveredRate: 142.67,
    inventoryValueMinor: 1_250_000n,
    inventoryItemCount: 5,
  },
  {
    id: "coffee-project",
    name: "مشروع القهوة",
    description: "تجهيز ركن قهوة متنقل",
    status: "active",
    projectType: "food",
    modules: {
      transactions: true,
      goal: false,
      workers: true,
      capital: true,
      inventory: true,
    livestock: false,
    },
    incomeMinor: 5_200_000n,
    expenseMinor: 3_150_000n,
    profitMinor: 2_050_000n,
    progress: 58,
    mark: "ق",
    tone: "bg-danger-soft text-danger",
    colorToken: "danger",
    outstandingLaborMinor: 450_000n,
    activeWorkers: 2,
    capitalMinor: 2_500_000n,
    capitalRecoveredRate: 82,
    inventoryValueMinor: 720_000n,
    inventoryItemCount: 12,
  },
  {
    id: "freelance",
    name: "العمل الحر",
    description: "مشاريع التصميم والاستشارات",
    status: "active",
    projectType: "services",
    modules: {
      transactions: true,
      goal: true,
      workers: true,
      capital: false,
      inventory: false,
    livestock: false,
    },
    incomeMinor: 1_800_000n,
    expenseMinor: 1_300_000n,
    profitMinor: 500_000n,
    progress: 46,
    mark: "ع",
    tone: "bg-info-soft text-info",
    colorToken: "info",
    outstandingLaborMinor: 0n,
    activeWorkers: 0,
    capitalMinor: 0n,
    capitalRecoveredRate: null,
    inventoryValueMinor: 0n,
    inventoryItemCount: 0,
  },
];
